FROM node:21 as build

ENV NODE_ENV production

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app
COPY . /app

RUN npm install
RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN rm -rf ./*

COPY --from=build /app/build .

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
