FROM node:21 as build

ENV NODE_ENV production

WORKDIR /frontend
COPY . /frontend

COPY package.json /frontend
COPY package-lock.json /frontend

RUN npm install
RUN npm i -g next@13.3.4
RUN next build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN rm -rf ./*

COPY --from=build /frontend/build .

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80
