FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN apt-get install -y redis-server

RUN mkdir /backend
WORKDIR /backend

CMD service redis-server start

COPY Gemfile /Gemfile
COPY Gemfile.lock /Gemfile.lock

COPY . /backend
RUN bundle install --without development test

EXPOSE 3000

CMD ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
